# Generated by Django 4.2.7 on 2025-11-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
