# Generated by Django 4.2.7 on 2025-11-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0003_alter_company_options'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the recruitment drive', max_length=200)),
                ('description', models.TextField(help_text='Description of the recruitment drive')),
                ('drive_date', models.DateTimeField(help_text='Date and time of the recruitment drive')),
                ('location', models.CharField(help_text='Location of the drive', max_length=200)),
                ('venue', models.CharField(help_text='Specific venue/room', max_length=200)),
                ('coordinator_notes', models.TextField(blank=True, help_text='Internal notes for coordinators', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Approved by coordinator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_drives', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_drives', to='jobs.jobposting')),
            ],
            options={
                'verbose_name': 'Recruitment Drive',
                'verbose_name_plural': 'Recruitment Drives',
                'ordering': ['-drive_date'],
            },
        ),
    ]
