# Generated by Django 4.2.7 on 2025-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('job_posted', 'New Job Posted'), ('application_received', 'Application Received'), ('application_status_changed', 'Application Status Changed'), ('interview_scheduled', 'Interview Scheduled'), ('announcement', 'Announcement'), ('job_recommendation', 'Job Recommendation')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField(blank=True, help_text='Optional link to related resource', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
