# Generated by Django 4.2.7 on 2025-11-08 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'job')},
        ),
    ]
